use_frameworks!

platform :ios, '9.0'

target 'LYFoundation_Example' do
  pod 'LYFoundation', :path => '../'

  target 'LYFoundation_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
